-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- USERS table is handled by Supabase Auth (auth.users)
-- We might need a public profile table if we want to store extra data, 
-- but the current python model only had email/password/active which Auth handles.
-- We will reference auth.users(id) directly.

-- PROBLEMS Table
create table public.problems (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  difficulty text not null default 'medium',
  tags jsonb default '[]'::jsonb,
  description text not null,
  ideal_solution_outline text,
  example_prompts_for_ai jsonb default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Problems (Public Read, Admin Write)
alter table public.problems enable row level security;

create policy "Problems are viewable by everyone"
  on public.problems for select
  using ( true );

-- SUBMISSIONS Table
create table public.submissions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  problem_id bigint not null references public.problems(id) on delete cascade,
  content text not null,
  status text not null default 'draft', -- 'draft', 'submitted', 'completed'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Submissions (Users manage their own)
alter table public.submissions enable row level security;

create policy "Users can view their own submissions"
  on public.submissions for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own submissions"
  on public.submissions for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own submissions"
  on public.submissions for update
  using ( auth.uid() = user_id );

-- AI INTERACTIONS Table
create table public.ai_interactions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  problem_id bigint references public.problems(id) on delete cascade,
  submission_id bigint references public.submissions(id) on delete set null,
  role text not null, -- 'hint', 'review', 'workflow'
  prompt text not null,
  response text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for AI Interactions (Users view their own)
alter table public.ai_interactions enable row level security;

create policy "Users can view their own AI interactions"
  on public.ai_interactions for select
  using ( auth.uid() = user_id );

-- Note: In the future, we might restrict INSERT to only be possible via Edge Functions (Service Role)
-- depending on how we architect the call. For now we allow insert if the user owns it,
-- but typically we want the Edge Function to write this record to ensure validity.
create policy "Users can insert their own AI interactions"
  on public.ai_interactions for insert
  with check ( auth.uid() = user_id );
